
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Reposcraper.Judger
{
    /// <summary>
    /// Judge that uses DeepSeek LLM for evaluating extracted data.
    /// </summary>
    public sealed class DeepSeekJudge : LlmJudge, IDisposable
    {
        /// <summary>
        /// Request payload for DeepSeek chat completions.
        /// </summary>
        private sealed class ChatRequest
        {
            /// <summary>
            /// Model to use for the chat completion.
            /// </summary>
            [JsonPropertyName("model")]
            public string Model { get; set; } = string.Empty;

            /// <summary>
            /// Gets or sets the collection of chat messages exchanged in the conversation.
            /// </summary>
            [JsonPropertyName("messages")]
            public List<ChatMessage> Messages { get; set; } = new();

            /// <summary>
            /// Controls the randomness of the output. Higher values like 0.8 will make the output more random,
            /// while lower values like 0.2 will make it more focused and deterministic.
            /// </summary>
            [JsonPropertyName("temperature")]
            public double Temperature { get; set; }

            /// <summary>
            /// Whether to stream the response or not.
            /// </summary>
            [JsonPropertyName("stream")]
            public bool Stream { get; set; } = false;
        }


        /// <summary>
        /// Represents a chat message in the DeepSeek chat completion API.
        /// </summary>
        private sealed class ChatMessage
        {
            /// <summary>
            /// Role of the message sender. Can be "system", "user", or "assistant".
            /// </summary>
            [JsonPropertyName("role")]
            public string Role { get; set; } = string.Empty;

            /// <summary>
            /// Content of the message.
            /// </summary>
            [JsonPropertyName("content")]
            public string Content { get; set; } = string.Empty;
        }

        /// <summary>
        /// Gets or sets the collection of choices returned in the chat response.
        /// </summary>
        /// <remarks>Each choice in the collection represents a possible completion or reply generated by
        /// the chat model. The list is initialized to an empty collection by default.</remarks>
        private sealed class ChatResponse
        {
            /// <summary>
            /// Gets or sets the collection of choices returned in the chat response.
            /// </summary>
            [JsonPropertyName("choices")]
            public List<Choice> Choices { get; set; } = new();
        }

        /// <summary>
        /// Represents a single choice in the DeepSeek chat response.
        /// </summary>
        private sealed class Choice
        {
            /// <summary>
            /// The chat message generated by the model for this choice.
            /// </summary>
            [JsonPropertyName("message")]
            public ChatMessage? Message { get; set; }
        }

        /// <summary>
        /// Default DeepSeek API endpoint.
        /// </summary>
        private const string DefaultEndpoint = "https://api.deepseek.ai/v1/chat/completions";

        /// <summary>
        /// HTTP client used for making requests to DeepSeek API.
        /// </summary>
        private readonly HttpClient _httpClient;

        /// <summary>
        /// API key for authenticating with DeepSeek API.
        /// </summary>
        private readonly string _apiKey;

        /// <summary>
        /// Model to use for DeepSeek chat completions.
        /// </summary>
        private readonly string _model;

        /// <summary>
        /// DeepSeek API endpoint.
        /// </summary>
        private readonly string _endpoint;

        /// <summary>
        /// Indicates whether this instance owns the HttpClient and should dispose it.
        /// </summary>
        private readonly bool _ownsClient;

        public DeepSeekJudge(string apiKey, string model = "deepseek-reasoner", string? endpoint = null, HttpClient? httpClient = null)
        {
            if (apiKey is null)
            {
                throw new ArgumentNullException(nameof(apiKey));
            }
            _apiKey = apiKey;
            _model = string.IsNullOrWhiteSpace(model) ? "deepseek-reasoner" : model;
            _endpoint = string.IsNullOrWhiteSpace(endpoint) ? DefaultEndpoint : endpoint!;
            _httpClient = httpClient ?? new HttpClient();
            _ownsClient = httpClient is null;
            _httpClient.DefaultRequestHeaders.UserAgent.ParseAdd($"ReposcraperJudge/{Reposcraper.Version}");
        }

        protected override async Task<string> CompleteAsync(string systemPromt, string userPrompt, CancellationToken ctoken = default)
        {
            ChatRequest payload = new ChatRequest
            {
                Model = _model,
                Messages =
                [
                    new ChatMessage { Role = "system", Content = systemPromt },
                    new ChatMessage { Role = "user", Content = userPrompt }
                ],
                Temperature = 0.2,
                Stream = false
            };

            using HttpRequestMessage http = new HttpRequestMessage(HttpMethod.Post, _endpoint)
            {
                Content = new StringContent(JsonSerializer.Serialize(payload, DefaultJsonOptions), Encoding.UTF8, "application/json")
            };
            http.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);

            using HttpResponseMessage response = await _httpClient.SendAsync(http, ctoken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();

            string body = await response.Content.ReadAsStringAsync(ctoken).ConfigureAwait(false);
            ChatResponse chatResponse = JsonSerializer.Deserialize<ChatResponse>(body, DefaultJsonOptions)
                ?? throw new InvalidOperationException("Failed to deserialize DeepSeek response.");

            string? content = chatResponse.Choices?.FirstOrDefault()?.Message?.Content;
            if (string.IsNullOrWhiteSpace(content))
            {
                throw new InvalidOperationException("DeepSeek did not return any content.");
            }

            return content;
        }

        public void Dispose()
        {
            // Dispose the HttpClient if this instance owns it
            if (_ownsClient)
            {
                _httpClient.Dispose();
            }
        }
    }
}
